# https://taskfile.dev

version: "3"

tasks:
  lint:
    cmds:
      - dotenvx run -- tflint
  plan:
    cmds:
      - dotenvx run -- terraform plan
  apply:
    cmds:
      - dotenvx run -- terraform apply
